CREATE TABLE GE_USUARIOS(
US_ID INT(11) NOT NULL AUTO_INCREMENT,
US_NOME VARCHAR(30) NOT NULL,
US_SENHA VARCHAR(30) NOT NULL,
PRIMARY KEY (US_ID));

INSERT INTO GE_USUARIOS (US_NOME, US_SENHA) VALUES ('admin', 'admin');